name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps (if available)
        run: pip install -r requirements.txt || true
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest -q
